"project_identifier" : "youtrack-widgets"
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/default.pot",
  "dest": "/widgets/teamcity-project-status-widget/default.pot",
  "translation": "/src/app/translations/teamcity-project-status-widget_%two_letters_code%.po"
 }
]
